#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, use the while and if.
i=1
while [ $i -le 20 ]; 
do
echo $i 
case $i in
4)
echo 'bad luck from China';;
9)
echo 'bad luck from Japan';;
17) 
echo 'bad luck from Italy';;
esac
((i++))
done
