#!/bin/bash
printf "%o\n" $(( $((5#$(echo "1a" | tr water 01234))) + $((5#$(echo "111" | tr stir. 01234))) )) | tr 01234567 bestchoprintf "%o\n" $(( $((5#$(echo "1a" | tr water 01234))) + $((5#$(echo "111" | tr stir. 01234))) )) | tr 01234567 bestchol
