#!/usr/bin/env bash
#
touch /var/run/myscript.pid
hi=$(pgrep -f /var/run/myscript.pid)
$hi > /var/run/myscript.pid

i=0
while [ $i -le 1 ]; 
do
        echo "To infinity and beyond"
        trap "echo 'I hate the kill command'" SIGTERM 
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm /var/run/myscript.pid" SIGQUIT SIGTERM
	trap "break" SIGQUIT SIGTERM
done

