#!/usr/bin/env bash
#PID file
dir(){
	rm /var/run/myscript.pid
exit
}

trap "echo I hate the kill command;dir" SIGTERM
trap "echo Y U no love me?!;dir" SIGINT
echo $$ >> /var/run/myscript.pid
i=0
while [ $i -eq 1 ]; do
	echo "To infinity and beyond"
done
