#!/usr/bin/env bash
#
if [ "$1" == "start" ]
then 
./manage_my_process & 
echo > /var/run/my_process.pid
echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
sudo pkill-f manage_my_process 
rm /var/run/my_process.pid
echo "manage_my_process stopped"

elif [ "$1" == "restart" ]

then
sudo pkill -f "$(cat /var/run/my_process.pid)"
rm /var/run/my_process.pid
./manage_my_process &
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
else
       	echo "Usage: manage_my_process {start|stop|restart}"
fi
