#!/usr/bin/env bash
#
if [ "${1}" == "start" ]
then 
./manage_my_process & 
touch /var/run/my_process.pid
hi=$(pgrep -f /var/run/my_process.pid)
$hi >> /var/run/my_process.pid
echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
echo "manage_my_process stopped"
kill manage_my_process 
rm -i /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
kill "$(cat /var/run/my_process.pid)"
rm /var/run/my_process.pid
./manage_my_process &
touch /var/run/my_process.pid
hi=$(pgrep -f /var/run/my_process.pid)
$hi >> /var/run/my_process.pid
echo "manage_my_process restarted"
else echo "Usage: manage_my_process {start|stop|restart}"
fi
